[2023-11-25T20:26:52.886+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-25T20:26:52.899+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-25T20:26:52.900+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T20:26:53.171+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-18 00:00:00+00:00
[2023-11-25T20:26:53.182+0000] {standard_task_runner.py:57} INFO - Started process 76 to run task
[2023-11-25T20:26:53.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-18T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpzlx6rq4f']
[2023-11-25T20:26:53.191+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask transform
[2023-11-25T20:26:53.252+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [running]> on host 17ac1e2d02c6
[2023-11-25T20:26:53.345+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-18T00:00:00+00:00'
[2023-11-25T20:26:53.821+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 36, in transform_data
    data = prep_data(data)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 51, in prep_data
    data['name'] = data['Name'].str.replace("*","",regex=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Name'
[2023-11-25T20:26:53.839+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231118T000000, start_date=20231125T202652, end_date=20231125T202653
[2023-11-25T20:26:53.856+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task transform ('Name'; 76)
[2023-11-25T20:26:53.885+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-25T20:26:53.906+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26T00:21:20.138+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T00:21:20.148+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T00:21:20.149+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T00:21:20.164+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-18 00:00:00+00:00
[2023-11-26T00:21:20.170+0000] {standard_task_runner.py:57} INFO - Started process 78 to run task
[2023-11-26T00:21:20.173+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-18T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpy42e06up']
[2023-11-26T00:21:20.177+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask transform
[2023-11-26T00:21:20.233+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [running]> on host decfc1fe5c09
[2023-11-26T00:21:20.323+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-18T00:00:00+00:00'
[2023-11-26T00:21:21.219+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T00:21:21.232+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231118T000000, start_date=20231126T002120, end_date=20231126T002121
[2023-11-26T00:21:21.277+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T00:21:21.302+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T01:51:56.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T01:51:56.272+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T01:51:56.272+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T01:51:56.286+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-18 00:00:00+00:00
[2023-11-26T01:51:56.293+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-11-26T01:51:56.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-18T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmprdj7m8r_']
[2023-11-26T01:51:56.300+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask transform
[2023-11-26T01:51:56.355+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [running]> on host 2011df1a4519
[2023-11-26T01:51:56.436+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-18T00:00:00+00:00'
[2023-11-26T01:52:14.638+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T01:52:14.652+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231118T000000, start_date=20231126T015156, end_date=20231126T015214
[2023-11-26T01:52:14.685+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T01:52:14.712+0000] {taskinstance.py:2778} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:41:01.362+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T02:41:01.431+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [queued]>
[2023-11-26T02:41:01.432+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T02:41:01.588+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-18 00:00:00+00:00
[2023-11-26T02:41:01.599+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-11-26T02:41:01.606+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-18T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmplzqfk6_7']
[2023-11-26T02:41:01.614+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask transform
[2023-11-26T02:41:01.721+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-18T00:00:00+00:00 [running]> on host d8c33f99ee50
[2023-11-26T02:41:02.029+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-18T00:00:00+00:00'
[2023-11-26T02:41:16.547+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:41:16.562+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231118T000000, start_date=20231126T024101, end_date=20231126T024116
[2023-11-26T02:41:16.607+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:41:16.639+0000] {taskinstance.py:2778} INFO - 4 downstream tasks scheduled from follow-on schedule check
