[2023-11-21T00:35:06.977+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-21T00:35:07.150+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-21T00:35:07.157+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T00:35:07.305+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-05 00:00:00+00:00
[2023-11-21T00:35:07.559+0000] {standard_task_runner.py:57} INFO - Started process 268 to run task
[2023-11-21T00:35:07.608+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpt9_92cti']
[2023-11-21T00:35:07.650+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask load
[2023-11-21T00:35:08.373+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-05T00:00:00+00:00 [running]> on host e947633e76f3
[2023-11-21T00:35:27.071+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-21T00:49:29.758+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to upstream_failed. Terminating instance.
[2023-11-21T00:49:33.208+0000] {process_utils.py:131} INFO - Sending 15 to group 268. PIDs of all processes in the group: [268]
[2023-11-21T00:49:33.259+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 268
[2023-11-21T00:49:39.327+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-11-21T00:50:24.895+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=268, status='terminated', exitcode=0, started='00:35:06') (268) terminated with exit code 0
