[2023-11-25T20:27:34.711+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-25T20:27:34.877+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-25T20:27:34.878+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T20:27:34.894+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-20 00:00:00+00:00
[2023-11-25T20:27:34.900+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-11-25T20:27:34.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpok4c_odm']
[2023-11-25T20:27:34.908+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask transform
[2023-11-25T20:27:34.958+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [running]> on host 17ac1e2d02c6
[2023-11-25T20:27:35.043+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-25T20:27:35.474+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 36, in transform_data
    data = prep_data(data)
  File "/opt/airflow/dags/etl_scripts/transform.py", line 51, in prep_data
    data['name'] = data['Name'].str.replace("*","",regex=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Name'
[2023-11-25T20:27:35.488+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=transform, execution_date=20231120T000000, start_date=20231125T202734, end_date=20231125T202735
[2023-11-25T20:27:35.505+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task transform ('Name'; 102)
[2023-11-25T20:27:35.522+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-25T20:27:35.551+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26T00:21:54.560+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26T00:21:54.582+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26T00:21:54.583+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T00:21:54.598+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-20 00:00:00+00:00
[2023-11-26T00:21:54.605+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2023-11-26T00:21:54.608+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp7tcquhe0']
[2023-11-26T00:21:54.612+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask transform
[2023-11-26T00:21:54.685+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [running]> on host decfc1fe5c09
[2023-11-26T00:21:54.879+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-26T00:21:55.962+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T00:21:55.974+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231120T000000, start_date=20231126T002154, end_date=20231126T002155
[2023-11-26T00:21:56.000+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T00:21:56.025+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26T01:52:59.480+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26T01:52:59.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26T01:52:59.495+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T01:52:59.522+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-20 00:00:00+00:00
[2023-11-26T01:52:59.532+0000] {standard_task_runner.py:57} INFO - Started process 153 to run task
[2023-11-26T01:52:59.536+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp1cx72k74']
[2023-11-26T01:52:59.540+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask transform
[2023-11-26T01:52:59.592+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [running]> on host 2011df1a4519
[2023-11-26T01:52:59.700+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-26T01:53:00.453+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T01:53:00.465+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231120T000000, start_date=20231126T015259, end_date=20231126T015300
[2023-11-26T01:53:00.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T01:53:00.547+0000] {taskinstance.py:2778} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-11-26T02:42:28.006+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26T02:42:28.026+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26T02:42:28.031+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T02:42:28.399+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-11-20 00:00:00+00:00
[2023-11-26T02:42:28.415+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2023-11-26T02:42:28.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'transform', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpcw4aca78']
[2023-11-26T02:42:28.431+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask transform
[2023-11-26T02:42:28.548+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.transform scheduled__2023-11-20T00:00:00+00:00 [running]> on host d8c33f99ee50
[2023-11-26T02:42:28.688+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-26T02:42:41.498+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-26T02:42:41.525+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=transform, execution_date=20231120T000000, start_date=20231126T024228, end_date=20231126T024241
[2023-11-26T02:42:41.597+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-26T02:42:41.628+0000] {taskinstance.py:2778} INFO - 4 downstream tasks scheduled from follow-on schedule check
